version: 2.1

orbs:
  python: circleci/python@2

jobs:
  test-python:
    docker:
      # Use Python 3.10 to be compatible with contourpy 1.3.1
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Install dependencies
          command: |
            # Create the virtual environment in the correct directory
            python -m venv venv
            # Activate the virtual environment
            . venv/bin/activate
            # Upgrade pip and install the dependencies
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit.xml

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy
          command: '#e.g. ./deploy.sh'

workflows:
  build-and-test:
    jobs:
      - test-python
    # Uncomment the following lines to add the deploy job to the workflow
    # - deploy:
    #     requires:
    #       - test-python


